import type { AmenityCategory } from "@prisma/client";

export interface AmenitySeedRow {
  code: string;
  name_ar: string;
  name_en: string;
  icon_name: string | null;
  category: AmenityCategory;
  sort_order: number;
  applies_to_vacation_rental: boolean;
  applies_to_vacation_rental_space: boolean;
  applies_to_hotel: boolean;
  applies_to_room_type: boolean;
}

/** Initial catalogue — ~22 rows covering each applicability flag pattern. */
export const AMENITY_SEEDS: AmenitySeedRow[] = [
  // Shared: vacation rental listing + hotel
  {
    code: "wifi",
    name_ar: "واي فاي",
    name_en: "Wi-Fi",
    icon_name: "Wifi",
    category: "essentials",
    sort_order: 10,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: true,
    applies_to_room_type: false,
  },
  {
    code: "parking",
    name_ar: "موقف سيارة",
    name_en: "Parking",
    icon_name: "ParkingSquare",
    category: "parking",
    sort_order: 20,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: true,
    applies_to_room_type: false,
  },
  {
    code: "ac",
    name_ar: "تكييف",
    name_en: "Air conditioning",
    icon_name: "Snowflake",
    category: "essentials",
    sort_order: 30,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: true,
    applies_to_room_type: true,
  },
  {
    code: "pool",
    name_ar: "مسبح",
    name_en: "Pool",
    icon_name: "Waves",
    category: "pool_spa",
    sort_order: 40,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: true,
    applies_to_room_type: false,
  },
  {
    code: "pets_allowed",
    name_ar: "تقبل حيوانات أليفة",
    name_en: "Pets allowed",
    icon_name: "PawPrint",
    category: "family",
    sort_order: 50,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: true,
    applies_to_room_type: false,
  },
  // Vacation rental listing only
  {
    code: "kitchen",
    name_ar: "مطبخ مجهز",
    name_en: "Equipped kitchen",
    icon_name: "Utensils",
    category: "kitchen",
    sort_order: 100,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: false,
    applies_to_room_type: false,
  },
  {
    code: "washing_machine",
    name_ar: "غسالة",
    name_en: "Washing machine",
    icon_name: "WashingMachine",
    category: "essentials",
    sort_order: 110,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: false,
    applies_to_room_type: false,
  },
  {
    code: "garden",
    name_ar: "حديقة",
    name_en: "Garden",
    icon_name: "Trees",
    category: "outdoor",
    sort_order: 120,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: false,
    applies_to_room_type: false,
  },
  {
    code: "barbecue",
    name_ar: "شواية",
    name_en: "Barbecue",
    icon_name: "Flame",
    category: "outdoor",
    sort_order: 130,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: false,
    applies_to_room_type: false,
  },
  {
    code: "workspace",
    name_ar: "مكان عمل",
    name_en: "Workspace",
    icon_name: "Laptop",
    category: "work",
    sort_order: 140,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: false,
    applies_to_room_type: false,
  },
  {
    code: "smoke_detector",
    name_ar: "كاشف دخان",
    name_en: "Smoke detector",
    icon_name: "ShieldAlert",
    category: "safety",
    sort_order: 150,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: false,
    applies_to_room_type: false,
  },
  // Vacation rental space only
  {
    code: "hair_dryer",
    name_ar: "مجفف شعر",
    name_en: "Hair dryer",
    icon_name: "Wind",
    category: "bathroom",
    sort_order: 200,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: true,
    applies_to_hotel: false,
    applies_to_room_type: false,
  },
  {
    code: "wardrobe",
    name_ar: "خزانة ملابس",
    name_en: "Wardrobe",
    icon_name: "Shirt",
    category: "bedroom",
    sort_order: 210,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: true,
    applies_to_hotel: false,
    applies_to_room_type: false,
  },
  {
    code: "blackout_curtains",
    name_ar: "ستائر معتمة",
    name_en: "Blackout curtains",
    icon_name: "Moon",
    category: "bedroom",
    sort_order: 220,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: true,
    applies_to_hotel: false,
    applies_to_room_type: true,
  },
  {
    code: "ensuite_bathroom",
    name_ar: "حمام داخلي",
    name_en: "Ensuite bathroom",
    icon_name: "Bath",
    category: "bathroom",
    sort_order: 230,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: true,
    applies_to_hotel: false,
    applies_to_room_type: false,
  },
  // Hotel only (minimal — Phase 4 expands catalogue)
  {
    code: "breakfast",
    name_ar: "إفطار مشمول",
    name_en: "Breakfast included",
    icon_name: "Coffee",
    category: "services",
    sort_order: 300,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: true,
    applies_to_room_type: false,
  },
  {
    code: "reception_24h",
    name_ar: "استقبال 24 ساعة",
    name_en: "24-hour reception",
    icon_name: "BellRing",
    category: "services",
    sort_order: 310,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: true,
    applies_to_room_type: false,
  },
  {
    code: "hotel_gym",
    name_ar: "صالة رياضية",
    name_en: "Gym",
    icon_name: "Dumbbell",
    category: "entertainment",
    sort_order: 320,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: true,
    applies_to_room_type: false,
  },
  {
    code: "spa",
    name_ar: "سبا",
    name_en: "Spa",
    icon_name: "Sparkles",
    category: "pool_spa",
    sort_order: 330,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: true,
    applies_to_room_type: false,
  },
  // Room type flag example (hotel room amenities later)
  {
    code: "minibar",
    name_ar: "ميني بار",
    name_en: "Minibar",
    icon_name: "Wine",
    category: "services",
    sort_order: 400,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: false,
    applies_to_hotel: false,
    applies_to_room_type: true,
  },
  {
    code: "tv",
    name_ar: "تلفزيون",
    name_en: "TV",
    icon_name: "Tv",
    category: "entertainment",
    sort_order: 410,
    applies_to_vacation_rental: false,
    applies_to_vacation_rental_space: true,
    applies_to_hotel: false,
    applies_to_room_type: true,
  },
  {
    code: "heating",
    name_ar: "تدفئة",
    name_en: "Heating",
    icon_name: "Thermometer",
    category: "essentials",
    sort_order: 420,
    applies_to_vacation_rental: true,
    applies_to_vacation_rental_space: true,
    applies_to_hotel: true,
    applies_to_room_type: true,
  },
];
